# Load Libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Unique Properties of numpy
- Mean
- Median
- Standard Deviation

In [3]:
data = np.array([1,2,3,4,5])

In [4]:
np.mean(data)

3.0

In [5]:
np.median(data)

3.0

In [7]:
np.std(data)

1.4142135623730951

# Compute the dot product of these array

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [10]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

# Element-wise operations. Add the 2 array

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [14]:
np.add(arr1,arr2)

array([ 6,  8, 10, 12])

In [15]:
np.subtract(arr1,arr2)

array([-4, -4, -4, -4])

In [17]:
arr1 * arr2

array([ 5, 12, 21, 32])

# Broadcasting

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
scalar =10

In [25]:
arr * scalar

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr_new = np.array([[10,10,10],[10,10,10]])

In [26]:
arr_new*arr

array([[10, 20, 30],
       [40, 50, 60]])

# Indexing in Numpy

In [27]:
monthly_sales1 = np.array([
    [280,320,400,350,300,380],
    [220,250,300,280,320,350],
    [300,350,380,400,420, 121]])
monthly_sales1

array([[280, 320, 400, 350, 300, 380],
       [220, 250, 300, 280, 320, 350],
       [300, 350, 380, 400, 420, 121]])

In [31]:
monthly_sales1.shape

(3, 6)

In [33]:
monthly_sales1[0,1]

320

In [45]:
monthly_sales1[1:,2:]

array([[300, 280, 320, 350],
       [380, 400, 420, 121]])

In [53]:
monthly_sales2 = np.array([
    [280,320,400,350,300,380],
    [220,250,300,280,320,350],
    [300,350,380,400,420, 121],
    [100,50,30,100,500,1000]])
monthly_sales2

array([[ 280,  320,  400,  350,  300,  380],
       [ 220,  250,  300,  280,  320,  350],
       [ 300,  350,  380,  400,  420,  121],
       [ 100,   50,   30,  100,  500, 1000]])

In [49]:
monthly_sales2.shape

(4, 6)

In [51]:
monthly_sales2[1:3,1:4]

array([[250, 300, 280],
       [350, 380, 400]])

# Creating a dataframe from nd_array, list and dictionaries

In [63]:
# Create dataframe with this NumPy array
data_np = np.array([[1,2,3],[4,5,6]])
data_np

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
df = pd.DataFrame(data_np)
df

0  1  2
0  1  2  3
1  4  5  6

In [57]:
# Create a series
data_list = [[10, 20, 30, 40, 50], [0,1,1,66,7], [0,5,6,7,2]]
data_list

[[10, 20, 30, 40, 50], [0, 1, 1, 66, 7], [0, 5, 6, 7, 2]]

In [60]:
df1 = pd.Series(data_list)
df1

0    [10, 20, 30, 40, 50]
1        [0, 1, 1, 66, 7]
2         [0, 5, 6, 7, 2]
dtype: object

In [65]:
# create a dataframe with this list
data_list1 = [[10, 20, 30, 40, 50], [0,1,1,66,7], [0,5,6,7,2]]
data_list1

[[10, 20, 30, 40, 50], [0, 1, 1, 66, 7], [0, 5, 6, 7, 2]]

In [92]:
df2 = pd.DataFrame(data = data_list1, index = ['R1', 'R2', 'R3'], columns = ['C1', 'C2', 'C3', 'C4', 'C5'])
df2

C1  C2  C3  C4  C5
R1  10  20  30  40  50
R2   0   1   1  66   7
R3   0   5   6   7   2

In [91]:
df2 = pd.DataFrame(data_list1,['Row 1', 'Row 2', 'Row 3'],['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5'])
df2

Column 1  Column 2  Column 3  Column 4  Column 5
Row 1        10        20        30        40        50
Row 2         0         1         1        66         7
Row 3         0         5         6         7         2

In [85]:
# create a dataframe with the dictionary below

sales_dict = {"Product 1": [1000, 2110, 3340, 40234, 2450],"product 2" :[1323,23221,23441,2626,272],
              "product 3" :[110,225,446,557,332]}
sales_dict

{'Product 1': [1000, 2110, 3340, 40234, 2450],
 'product 2': [1323, 23221, 23441, 2626, 272],
 'product 3': [110, 225, 446, 557, 332]}

In [98]:
sales_df = pd.DataFrame(sales_dict)
sales_df

Product 1  product 2  product 3
0       1000       1323        110
1       2110      23221        225
2       3340      23441        446
3      40234       2626        557
4       2450        272        332

# PANDAS

### Read Data

In [139]:
data = pd.read_csv("Loan_default.csv")
data

LoanID  Age   Income  LoanAmount  CreditScore  MonthsEmployed  \
0       I38PQUQS96   56  85994.0       50587          520            80.0   
1       HPSK72WA7R   69  50432.0      124440          458            15.0   
2       C1OZ6DPJ8Y   46  84208.0      129188          451            26.0   
3       V2KKSFM3UN   32  31713.0       44799          743             0.0   
4       EY08JDHTZP   60      NaN        9139          633             8.0   
...            ...  ...      ...         ...          ...             ...   
255342  8C6S86ESGC   19  37979.0      210682          541           109.0   
255343  98R4KDHNND   32  51953.0      189899          511            14.0   
255344  XQK1UUUNGP   56  84820.0      208294          597            70.0   
255345  JAO28CPL4H   42  85109.0       60575          809            40.0   
255346  ZTH91CGL0B   62  22418.0       18481          636           113.0   

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0                  4.0         15.23        36      0.44   Bachelor's   
1                  1.0          4.81        60      0.68     Master's   
2                  3.0         21.17        24      0.31     Master's   
3                  3.0          7.07        24      0.23  High School   
4                  4.0           NaN        48      0.73   Bachelor's   
...                ...           ...       ...       ...          ...   
255342             4.0         14.11        12      0.85   Bachelor's   
255343             2.0         11.55        24      0.21  High School   
255344             3.0          5.29        60      0.50  High School   
255345             1.0         20.90        48      0.44  High School   
255346             2.0          6.73        12      0.48   Bachelor's   

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0           Full-time      Divorced         Yes           Yes       Other   
1           Full-time       Married          No            No       Other   
2          Unemployed      Divorced         Yes           Yes        Auto   
3           Full-time       Married          No            No    Business   
4          Unemployed      Divorced          No           Yes        Auto   
...               ...           ...         ...           ...         ...   
255342      Full-time       Married          No            No       Other   
255343      Part-time      Divorced          No            No        Home   
255344  Self-employed       Married         Yes           Yes        Auto   
255345      Part-time        Single         Yes           Yes       Other   
255346     Unemployed      Divorced         Yes            No   Education   

       HasCoSigner  Default  
0              Yes        0  
1              Yes        0  
2               No        1  
3               No        0  
4               No        0  
...            ...      ...  
255342          No        0  
255343          No        1  
255344         Yes        0  
255345          No        0  
255346         Yes        0  

[255347 rows x 18 columns]

### Drop loanID

In [151]:
data1 = data.drop(['LoanID'], axis = 1)
data1.head()

Age   Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56  85994.0       50587          520            80.0             4.0   
1   69  50432.0      124440          458            15.0             1.0   
2   46  84208.0      129188          451            26.0             3.0   
3   32  31713.0       44799          743             0.0             3.0   
4   60      NaN        9139          633             8.0             4.0   

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced   
1          4.81        60      0.68     Master's      Full-time       Married   
2         21.17        24      0.31     Master's     Unemployed      Divorced   
3          7.07        24      0.23  High School      Full-time       Married   
4           NaN        48      0.73   Bachelor's     Unemployed      Divorced   

  HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0         Yes           Yes       Other         Yes        0  
1          No            No       Other         Yes        0  
2         Yes           Yes        Auto          No        1  
3          No            No    Business          No        0  
4          No           Yes        Auto          No        0

In [152]:
data1.tail()

Age   Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
255342   19  37979.0      210682          541           109.0             4.0   
255343   32  51953.0      189899          511            14.0             2.0   
255344   56  84820.0      208294          597            70.0             3.0   
255345   42  85109.0       60575          809            40.0             1.0   
255346   62  22418.0       18481          636           113.0             2.0   

        InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
255342         14.11        12      0.85   Bachelor's      Full-time   
255343         11.55        24      0.21  High School      Part-time   
255344          5.29        60      0.50  High School  Self-employed   
255345         20.90        48      0.44  High School      Part-time   
255346          6.73        12      0.48   Bachelor's     Unemployed   

       MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  \
255342       Married          No            No       Other          No   
255343      Divorced          No            No        Home          No   
255344       Married         Yes           Yes        Auto         Yes   
255345        Single         Yes           Yes       Other          No   
255346      Divorced         Yes            No   Education         Yes   

        Default  
255342        0  
255343        1  
255344        0  
255345        0  
255346        0

### Check descriptive statistics

In [156]:
data1.describe().T

count           mean           std      min       25%  \
Age             255347.0      43.498306     14.990258     18.0     31.00   
Income          255339.0   82499.629074  38962.863250  15000.0  48826.00   
LoanAmount      255347.0  127578.865512  70840.706142   5000.0  66156.00   
CreditScore     255347.0     574.264346    158.903867    300.0    437.00   
MonthsEmployed  255329.0      59.541313     34.643650      0.0     30.00   
NumCreditLines  255339.0       2.501040      1.117018      1.0      2.00   
InterestRate    255344.0      13.492814      6.636434      2.0      7.77   
LoanTerm        255347.0      36.025894     16.969330     12.0     24.00   
DTIRatio        255347.0       0.500212      0.230917      0.1      0.30   
Default         255347.0       0.116128      0.320379      0.0      0.00   

                      50%        75%       max  
Age                 43.00      56.00      69.0  
Income           82466.00  116219.00  149999.0  
LoanAmount      127556.00  188985.00  249999.0  
CreditScore        574.00     712.00     849.0  
MonthsEmployed      60.00      90.00     119.0  
NumCreditLines       2.00       3.00       4.0  
InterestRate        13.46      19.25      25.0  
LoanTerm            36.00      48.00      60.0  
DTIRatio             0.50       0.70       0.9  
Default              0.00       0.00       1.0

There are missing values - Inconsistent count across all features

### Check for missing values - .fillna()

In [159]:
data.isnull().sum()

LoanID             0
Age                0
Income             8
LoanAmount         0
CreditScore        0
MonthsEmployed    18
NumCreditLines     8
InterestRate       3
LoanTerm           0
DTIRatio           0
Education          0
EmploymentType     0
MaritalStatus      0
HasMortgage        0
HasDependents      0
LoanPurpose        0
HasCoSigner        0
Default            0
dtype: int64

In [160]:
data1.head()

Age   Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56  85994.0       50587          520            80.0             4.0   
1   69  50432.0      124440          458            15.0             1.0   
2   46  84208.0      129188          451            26.0             3.0   
3   32  31713.0       44799          743             0.0             3.0   
4   60      NaN        9139          633             8.0             4.0   

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced   
1          4.81        60      0.68     Master's      Full-time       Married   
2         21.17        24      0.31     Master's     Unemployed      Divorced   
3          7.07        24      0.23  High School      Full-time       Married   
4           NaN        48      0.73   Bachelor's     Unemployed      Divorced   

  HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0         Yes           Yes       Other         Yes        0  
1          No            No       Other         Yes        0  
2         Yes           Yes        Auto          No        1  
3          No            No    Business          No        0  
4          No           Yes        Auto          No        0

In [184]:
data1['Income']

0         85994.0
1         50432.0
2         84208.0
3         31713.0
4         82466.0
           ...   
255342    37979.0
255343    51953.0
255344    84820.0
255345    85109.0
255346    22418.0
Name: Income, Length: 255347, dtype: float64

In [193]:
# Calculate the median for Income
income_median = data1['Income'].median()

# Replace missing value in Income_median
data1['Income'] = data1['Income'].fillna(income_median)

In [194]:
# Calculate the median for MonthsEmployed
MonthsEmployed_median = data1['MonthsEmployed'].median()

# Replace missing value in MonthsEmployed_median
data1['MonthsEmployed'] = data1['MonthsEmployed'].fillna(MonthsEmployed_median)

In [177]:
# Calculate the median for NumCreditLines
NumCreditLines_median = data1['NumCreditLines'].median()

# Replace missing value in NumCreditLines_median
data1['NumCreditLines'] = data1['NumCreditLines'].fillna(NumCreditLines_median)

In [179]:
# Calculate the median for InterestRate
InterestRate_median = data1['InterestRate'].median()

# Replace missing value in InterestRate_median
data1['InterestRate'] = data1['InterestRate'].fillna(InterestRate_median)

In [191]:
# SUMMARY
# Check for column_with_na
column_with_na = ['Income', 'MonthsEmployed', 'NumCreditLines', 'InterestRate']

for column in column_with_na:
    median = data1[column].median()
    
    data1[column] = data1[column].fillna(median)

In [192]:
data1.isnull().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

### Check for dtypes

In [198]:
data1.dtypes

Age                 int64
Income            float64
LoanAmount          int64
CreditScore         int64
MonthsEmployed    float64
NumCreditLines    float64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education          object
EmploymentType     object
MaritalStatus      object
HasMortgage        object
HasDependents      object
LoanPurpose        object
HasCoSigner        object
Default             int64
dtype: object

In [201]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Age             255347 non-null  int64  
 1   Income          255347 non-null  float64
 2   LoanAmount      255347 non-null  int64  
 3   CreditScore     255347 non-null  int64  
 4   MonthsEmployed  255347 non-null  float64
 5   NumCreditLines  255347 non-null  float64
 6   InterestRate    255347 non-null  float64
 7   LoanTerm        255347 non-null  int64  
 8   DTIRatio        255347 non-null  float64
 9   Education       255347 non-null  object 
 10  EmploymentType  255347 non-null  object 
 11  MaritalStatus   255347 non-null  object 
 12  HasMortgage     255347 non-null  object 
 13  HasDependents   255347 non-null  object 
 14  LoanPurpose     255347 non-null  object 
 15  HasCoSigner     255347 non-null  object 
 16  Default         255347 non-null  int64  
dtypes: float64

### Drop duplicates

In [204]:
data1.head(10)

Age    Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56   85994.0       50587          520            80.0             4.0   
1   69   50432.0      124440          458            15.0             1.0   
2   46   84208.0      129188          451            26.0             3.0   
3   32   31713.0       44799          743             0.0             3.0   
4   60   82466.0        9139          633             8.0             4.0   
5   25   90298.0       90448          720            18.0             2.0   
6   38  111188.0      177025          429            60.0             1.0   
7   56  126802.0      155511          531            67.0             4.0   
8   36   42053.0       92357          827            83.0             1.0   
9   40  132784.0      228510          480           114.0             4.0   

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced   
1          4.81        60      0.68     Master's      Full-time       Married   
2         21.17        24      0.31     Master's     Unemployed      Divorced   
3          7.07        24      0.23  High School      Full-time       Married   
4         13.46        48      0.73   Bachelor's     Unemployed      Divorced   
5         22.72        24      0.10  High School     Unemployed        Single   
6         19.11        12      0.16   Bachelor's     Unemployed        Single   
7          8.15        60      0.43          PhD      Full-time       Married   
8         23.94        48      0.20   Bachelor's  Self-employed      Divorced   
9          9.09        48      0.33  High School  Self-employed       Married   

  HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0         Yes           Yes       Other         Yes        0  
1          No            No       Other         Yes        0  
2         Yes           Yes        Auto          No        1  
3          No            No    Business          No        0  
4          No           Yes        Auto          No        0  
5         Yes            No    Business         Yes        1  
6         Yes            No        Home         Yes        0  
7          No            No        Home         Yes        0  
8         Yes            No   Education          No        1  
9         Yes            No       Other         Yes        0

In [206]:
data1 = data1.drop_duplicates(keep = 'first', ignore_index = True)

In [207]:
data1.head()

Age   Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56  85994.0       50587          520            80.0             4.0   
1   69  50432.0      124440          458            15.0             1.0   
2   46  84208.0      129188          451            26.0             3.0   
3   32  31713.0       44799          743             0.0             3.0   
4   60  82466.0        9139          633             8.0             4.0   

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced   
1          4.81        60      0.68     Master's      Full-time       Married   
2         21.17        24      0.31     Master's     Unemployed      Divorced   
3          7.07        24      0.23  High School      Full-time       Married   
4         13.46        48      0.73   Bachelor's     Unemployed      Divorced   

  HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0         Yes           Yes       Other         Yes        0  
1          No            No       Other         Yes        0  
2         Yes           Yes        Auto          No        1  
3          No            No    Business          No        0  
4          No           Yes        Auto          No        0

### Inspect categorical features

In [210]:
data1

Age   Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0        56  85994.0       50587          520            80.0             4.0   
1        69  50432.0      124440          458            15.0             1.0   
2        46  84208.0      129188          451            26.0             3.0   
3        32  31713.0       44799          743             0.0             3.0   
4        60  82466.0        9139          633             8.0             4.0   
...     ...      ...         ...          ...             ...             ...   
255342   19  37979.0      210682          541           109.0             4.0   
255343   32  51953.0      189899          511            14.0             2.0   
255344   56  84820.0      208294          597            70.0             3.0   
255345   42  85109.0       60575          809            40.0             1.0   
255346   62  22418.0       18481          636           113.0             2.0   

        InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
0              15.23        36      0.44   Bachelor's      Full-time   
1               4.81        60      0.68     Master's      Full-time   
2              21.17        24      0.31     Master's     Unemployed   
3               7.07        24      0.23  High School      Full-time   
4              13.46        48      0.73   Bachelor's     Unemployed   
...              ...       ...       ...          ...            ...   
255342         14.11        12      0.85   Bachelor's      Full-time   
255343         11.55        24      0.21  High School      Part-time   
255344          5.29        60      0.50  High School  Self-employed   
255345         20.90        48      0.44  High School      Part-time   
255346          6.73        12      0.48   Bachelor's     Unemployed   

       MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  \
0           Divorced         Yes           Yes       Other         Yes   
1            Married          No            No       Other         Yes   
2           Divorced         Yes           Yes        Auto          No   
3            Married          No            No    Business          No   
4           Divorced          No           Yes        Auto          No   
...              ...         ...           ...         ...         ...   
255342       Married          No            No       Other          No   
255343      Divorced          No            No        Home          No   
255344       Married         Yes           Yes        Auto         Yes   
255345        Single         Yes           Yes       Other          No   
255346      Divorced         Yes            No   Education         Yes   

        Default  
0             0  
1             0  
2             1  
3             0  
4             0  
...         ...  
255342        0  
255343        1  
255344        0  
255345        0  
255346        0  

[255347 rows x 17 columns]

In [216]:
categorical_cols = data1.select_dtypes(include = 'object')
categorical_cols.head()

Education EmploymentType MaritalStatus HasMortgage HasDependents  \
0   Bachelor's      Full-time      Divorced         Yes           Yes   
1     Master's      Full-time       Married          No            No   
2     Master's     Unemployed      Divorced         Yes           Yes   
3  High School      Full-time       Married          No            No   
4   Bachelor's     Unemployed      Divorced          No           Yes   

  LoanPurpose HasCoSigner  
0       Other         Yes  
1       Other         Yes  
2        Auto          No  
3    Business          No  
4        Auto          No

In [217]:
categorical_cols['Education'].unique()

array(["Bachelor's", "Master's", 'High School', 'PhD'], dtype=object)

In [220]:
categorical_cols['EmploymentType'].unique()

array(['Full-time', 'Unemployed', 'Self-employed', 'Part-time'],
      dtype=object)

In [231]:
#SUMMARY
list_of_cat_cols = categorical_cols.columns.to_list()

for column in list_of_cat_cols:
    print(column)

Education
EmploymentType
MaritalStatus
HasMortgage
HasDependents
LoanPurpose
HasCoSigner


In [229]:
for column in list_of_cat_cols:
    print(categorical_cols[column].unique())
    print("########################################################")

["Bachelor's" "Master's" 'High School' 'PhD']
########################################################
['Full-time' 'Unemployed' 'Self-employed' 'Part-time']
########################################################
['Divorced' 'Married' 'Single']
########################################################
['Yes' 'No']
########################################################
['Yes' 'No']
########################################################
['Other' 'Auto' 'Business' 'Home' 'Education']
########################################################
['Yes' 'No']
########################################################


### Save Cleaned Data

In [230]:
data1.to_csv('Clean_df.csv', index = False)